import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import Logo from "../../public/images/logo.gif";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col justify-center items-center h-screen">
        <div className="-translate-y-8 px-5">
          <Image src={Logo.src} width={397} height={100} alt="toniagost logo" />
        </div>
      </div>
    </>
  );
};

export default Home;
