import type { NextPage } from "next";
import Head from "next/head";

const Pictures: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col justify-center items-center h-screen">
        Pictures
      </main>
    </>
  );
};

export default Pictures;
